default: &default
  adapter: postgresql 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: reactworkshop_development 

test:
  <<: *default
  database: reactworkshop_test

production:
  <<: *default
  database: reactworkshop_production
